name: Compile progs.dat
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: Compile progs.dat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile using fteqcc
        run: |
          chmod +x ./keepsrc/fteqcc64
          cd ./keepsrc
          ./fteqcc64 -v -Fkce -Fifvector -Fvectorlogic
      - name: Upload progs.dat
        uses: actions/upload-artifact@v3
        with:
          name: progs.dat
          path: progs.dat
