name: Compile csprogs.dat
on:
  workflow_dispatch:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Compile csprogs.dat
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile using fteqcc
        run: |
          chmod +x ./keepsrc/fteqcc64
          cd ./keepsrc
          ./fteqcc64 -v -Fkce -Fifvector -Fvectorlogic -src ./csqc -srcfile ./csprogs.src
      - name: Upload csprogs.dat
        uses: actions/upload-artifact@v4
        with:
          name: csprogs.dat
          path: csprogs.dat
